Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Controllers/Weixin/TenPay/TenPayController.cs
/*----------------------------------------------------------------
    Copyright (C) 2021 Senparc
    
    文件名：TenPayController.cs
    文件功能描述：微信支付Controller
    
    
    创建标识：Senparc - 20150312
----------------------------------------------------------------*/

//DPBMARK_FILE TenPay
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Senparc.CO2NET.Extensions;
using Senparc.CO2NET.Helpers;
using Senparc.Weixin.HttpUtility;
using Senparc.Weixin.TenPay.V2;

//DPBMARK MP
using Senparc.Weixin.MP.AdvancedAPIs;
using Senparc.Weixin.MP.Containers;
using Senparc.Weixin.MP.Helpers;
//DPBMARK_END

namespace Senparc.Weixin.Sample.NetCore3.Controllers
{
    /// <summary>
    /// 根据官方的Webforms Demo改写，所以可以看到直接result +=)之类的用法，实际项目中不提倡这么做。
    /// 注意：此Controller中的Demo为早期的微信支付，最新的V3微信支付请见TenPayV3Controller
    /// </summary>
    public class TenPayController : BaseController
    {
        private static TenPayInfo _tenPayInfo;

        public static TenPayInfo TenPayInfo
        {
            get
            {
                if (_tenPayInfo == null)
                {
                    _tenPayInfo = 
                        TenPayInfoCollection.Data[Config.SenparcWeixinSetting.WeixinPay_PartnerId];
                }
                return _tenPayInfo;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FeedBack()
        {
            //创建支付应答对象
            ResponseHandler resHandler = new ResponseHandler(null);
            resHandler.Init();
            resHandler.SetKey(TenPayInfo.Key, TenPayInfo.AppKey);

            string result = String.Empty;

            //判断签名
            if (resHandler.IsWXsignfeedback())
            {
                //回复服务器处理成功
                result+="OK";
                result+= "OK:" + resHandler.GetDebugInfo();
            }
            else
            {
                //sha1签名失败
                result+= "fail";
                result+= "fail:" + resHandler.GetDebugInfo();
            }
            return Content(result);
        }

        public ActionResult JsApi()
        {
            //string appId = TenPayInfo.AppId;
            string timeStamp = "";
            string nonceStr = "";
            string packageValue = "";
            string paySign = "";

            string sp_billno = Request.Form["order_no"];
            //当前时间 yyyyMMdd
            string date = SystemTime.Now.ToString("yyyyMMdd");

            if (null == sp_billno)
            {
                //生成订单10位序列号，此处用时间和随机数生成，商户根据自己调整，保证唯一
                sp_billno = SystemTime.Now.ToString("HHmmss") + TenPayUtil.BuildRandomStr(4);
            }
            else
            {
                sp_billno = Request.Form["order_no"].ToString();
            }

            sp_billno = TenPayInfo.PartnerId + sp_billno;

            //创建支付应答对象
            RequestHandler packageReqHandler = new RequestHandler(null);
            //初始化
            packageReqHandler.Init();
            packageReqHandler.SetKey(TenPayInfo.Key);

            //设置package订单参数
            packageReqHandler.SetParameter("partner", TenPayInfo.PartnerId);		  //商户号
            packageReqHandler.SetParameter("fee_type", "1");                    //币种，1人民币
            packageReqHandler.SetParameter("input_charset", "GBK");
            packageReqHandler.SetParameter("bank_type", "WX");
            packageReqHandler.SetParameter("out_trade_no", sp_billno);		//商家订单号
            packageReqHandler.SetParameter("total_fee", "1");			        //商品金额,以分为单位(money * 100).ToString()
            packageReqHandler.SetParameter("notify_url", TenPayInfo.TenPayNotify);		    //接收财付通通知的URL
            packageReqHandler.SetParameter("body", "JSAPIdemo");	                    //商品描述
            packageReqHandler.SetParameter("spbill_create_ip", HttpContext.UserHostAddress()?.ToString());   //用户的公网ip，不是商户服务器IP

            //获取package包
            packageValue = packageReqHandler.GetRequestURL();

            //调起微信支付签名
            timeStamp = TenPayUtil.GetTimestamp();
            nonceStr = TenPayUtil.GetNoncestr();

            //设置支付参数
            RequestHandler paySignReqHandler = new RequestHandler(null);
            paySignReqHandler.SetParameter("appid", TenPayInfo.AppId);
            paySignReqHandler.SetParameter("appkey", TenPayInfo.AppKey);
            paySignReqHandler.SetParameter("noncestr", nonceStr);
            paySignReqHandler.SetParameter("timestamp", timeStamp);
            paySignReqHandler.SetParameter("package", packageValue);
            paySign = paySignReqHandler.CreateSHA1Sign();
            //TenPay.Delivernotify(TenPayInfo.AppId, "oX99MDgNcgwnz3zFN3DNmo8uwa-w", "111112222233333", sp_billno,
            //                     timeStamp, "1", "ok", "53cca9d47b883bd4a5c85a9300df3da0cb48565c", "sha1");


            //获取debug信息,建议把请求和debug信息写入日志，方便定位问题
            //string pakcageDebuginfo = packageReqHandler.getDebugInfo();
            //result +="<br/>pakcageDebuginfo:" + pakcageDebuginfo + "<br/>");
            //string paySignDebuginfo = paySignReqHandler.getDebugInfo();
            //result +="<br/>paySignDebuginfo:" + paySignDebuginfo + "<br/>");

            //TODO：和JSSDK一样整合信息包
            ViewData["appId"] = TenPayInfo.AppId;
            ViewData["timeStamp"] = timeStamp;
            ViewData["nonceStr"] = nonceStr;
            ViewData["packageValue"] = packageValue;
            ViewData["paySign"] = paySign;

            return View();
        }


        public ActionResult Native()
        {
            string sp_billno = Request.Form["order_no"];
            //当前时间 yyyyMMdd
            string date = SystemTime.Now.ToString("yyyyMMdd");

            if (null == sp_billno)
            {
                //生成订单10位序列号，此处用时间和随机数生成，商户根据自己调整，保证唯一
                sp_billno = SystemTime.Now.ToString("HHmmss") + TenPayUtil.BuildRandomStr(4);
            }
            else
            {
                sp_billno = Request.Form["order_no"].ToString();
            }

            sp_billno = TenPayInfo.PartnerId + sp_billno;


            RequestHandler outParams = new RequestHandler(null);

            outParams.Init();
            string productid = sp_billno;
            string timeStamp = TenPayUtil.GetTimestamp();
            string nonceStr = TenPayUtil.GetNoncestr();

            RequestHandler Params = new RequestHandler(null);
            Params.SetParameter("appid", TenPayInfo.AppId);
            Params.SetParameter("appkey", TenPayInfo.AppKey);
            Params.SetParameter("noncestr", nonceStr);
            Params.SetParameter("timestamp", timeStamp);
            Params.SetParameter("productid", productid);
            string sign = Params.CreateSHA1Sign();
            Params.SetParameter("sign", sign);

            var parm = TenPay.V2.TenPay.NativePay(TenPayInfo.AppId, timeStamp, nonceStr, productid, sign);
            parm = QRCode.QRfromGoogle(parm);
            ViewData["parm"] = parm;
            return View();
        }

        public ActionResult NativeCall()
        {
            string sp_billno = Request.Form["order_no"];
            //当前时间 yyyyMMdd
            string date = SystemTime.Now.ToString("yyyyMMdd");
            //订单号，此处用时间和随机数生成，商户根据自己调整，保证唯一
            string out_trade_no = "" + SystemTime.Now.ToString("HHmmss") + TenPayUtil.BuildRandomStr(4);

            if (null == sp_billno)
            {
                //生成订单10位序列号，此处用时间和随机数生成，商户根据自己调整，保证唯一
                sp_billno = SystemTime.Now.ToString("HHmmss") + TenPayUtil.BuildRandomStr(4);
            }
            else
            {
                sp_billno = Request.Form["order_no"].ToString();
            }

            sp_billno = TenPayInfo.PartnerId + sp_billno;



            //创建RequestHandler实例
            RequestHandler packageReqHandler = new RequestHandler(null);
            //初始化
            packageReqHandler.Init();
            packageReqHandler.SetKey(TenPayInfo.Key);

            //设置package订单参数
            packageReqHandler.SetParameter("partner", TenPayInfo.PartnerId);		  //商户号
            packageReqHandler.SetParameter("bank_type", "WX");		                      //银行类型
            packageReqHandler.SetParameter("fee_type", "1");                    //币种，1人民币
            packageReqHandler.SetParameter("input_charset", "GBK");
            packageReqHandler.SetParameter("out_trade_no", sp_billno);		//商家订单号
            packageReqHandler.SetParameter("total_fee", "1");			        //商品金额,以分为单位(money * 100).ToString()
            packageReqHandler.SetParameter("notify_url", TenPayInfo.TenPayNotify);		    //接收财付通通知的URL
            packageReqHandler.SetParameter("body", "nativecall");	                    //商品描述
            packageReqHandler.SetParameter("spbill_create_ip", "8.8.8.8"/*Page.Request.UserHostAddress*/);   //用户的公网ip，不是商户服务器IP

            //获取package包
            string packageValue = packageReqHandler.GetRequestURL();

            //调起微信支付签名
            string timeStamp = TenPayUtil.GetTimestamp();
            string nonceStr = TenPayUtil.GetNoncestr();

            //设置支付参数
            RequestHandler payHandler = new RequestHandler(null);
            payHandler.SetParameter("appid", TenPayInfo.AppId);
            payHandler.SetParameter("noncestr", nonceStr);
            payHandler.SetParameter("timestamp", timeStamp);
            payHandler.SetParameter("package", packageValue);
            payHandler.SetParameter("RetCode", "0");
            payHandler.SetParameter("RetErrMsg", "成功");
            string paySign = payHandler.CreateSHA1Sign();
            payHandler.SetParameter("app_signature", paySign);
            payHandler.SetParameter("sign_method", "SHA1");


            Response.ContentType = "text/xml";
            Response.Clear();
            ViewData["payHandler"] = payHandler.ParseXML();

            return View();
        }

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/Delivernotify.cshtml
@*DPBMARK_FILE TenPay*@
@{

                Layout = null;
}

<html>
<head>
    <title>Delivernotify</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            @ViewData["message"]
        </div>
    </form>
</body>
</html>

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/FeedBack.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/Index.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>微信支付测试跳转页</title>

</head>
<body>
    <div>
        <a href="@Url.Action("JsApi","TenPay")">jsapi支付</a>
        <a href="@Url.Action("FeedBack","TenPay")">FeedBack</a>
        <a href="@Url.Action("Native","TenPay")">native支付</a>
        <a href="@Url.Action("NativeCall","TenPay")">nativecall</a>
        <a href="@Url.Action("PayNotifyUrl","TenPay")">PayNotifyUrl</a>
        <a href="@Url.Action("Delivernotify","TenPay")">Delivernotify</a>
        <a href="@Url.Action("SharedAddress","TenPay")">SharedAddress</a>
    </div>
</body>
</html>

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/JsApi.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>公众号jsapi支付测试网页</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            background: #eae9e6;
        }

        body, p, table, td, th {
            font-size: 14px;
            font-family: helvetica,Arial,Tahoma;
        }

        h1 {
            font-family: Baskerville,HelveticaNeue-Bold,helvetica,Arial,Tahoma;
        }

        a {
            text-decoration: none;
            color: #385487;
        }


        .container {
        }

        .title {
        }

        #content {
            padding: 30px 20px 20px;
            color: #111;
            background: #f7f2ed;
        }

        .seeAlso {
            padding: 15px 20px 30px;
        }

        .headpic div {
            margin: 20px 0 0;
        }

        .headpic img {
            display: block;
        }

        .title h1 {
            font-size: 22px;
            font-weight: bold;
            padding: 0;
            margin: 0;
            line-height: 1.2;
            color: #1f1f1f;
        }

        .title p {
            color: #aaa;
            font-size: 12px;
            margin: 5px 0 0;
            padding: 0;
            font-weight: bold;
        }

        .pic {
            margin: 20px 0;
        }

        .articlecontent img {
            display: block;
            clear: both;
            margin: 5px auto;
        }

        .articlecontent p {
            text-indent: 2em;
            font-family: Georgia,helvetica,Arial,Tahoma;
            line-height: 1.4;
            font-size: 16px;
            margin: 20px 0;
        }


        .seeAlso h3 {
            font-size: 16px;
            color: #a5a5a5;
        }

        .seeAlso ul {
            margin: 0;
            padding: 0;
        }

        .seeAlso li {
            font-size: 16px;
            list-style-type: none;
            border-top: 1px solid #ccc;
            padding: 2px 0;
        }

            .seeAlso li a {
                border-bottom: none;
                display: block;
                line-height: 1.1;
                padding: 13px 0;
            }

        .clr {
            clear: both;
            height: 1px;
            overflow: hidden;
        }


        .fontSize1 .title h1 {
            font-size: 20px;
        }

        .fontSize1 .articlecontent p {
            font-size: 14px;
        }

        .fontSize1 .weibo .nickname, .fontSize1 .weibo .comment {
            font-size: 11px;
        }

        .fontSize1 .moreOperator {
            font-size: 14px;
        }

        .fontSize2 .title h1 {
            font-size: 22px;
        }

        .fontSize2 .articlecontent p {
            font-size: 16px;
        }

        .fontSize2 .weibo .nickname, .fontSize2 .weibo .comment {
            font-size: 13px;
        }

        .fontSize2 .moreOperator {
            font-size: 16px;
        }

        .fontSize3 .title h1 {
            font-size: 24px;
        }

        .fontSize3 .articlecontent p {
            font-size: 18px;
        }

        .fontSize3 .weibo .nickname, .fontSize3 .weibo .comment {
            font-size: 15px;
        }

        .fontSize3 .moreOperator {
            font-size: 18px;
        }

        .fontSize4 .title h1 {
            font-size: 26px;
        }

        .fontSize4 .articlecontent p {
            font-size: 20px;
        }

        .fontSize4 .weibo .nickname, .fontSize4 .weibo .comment {
            font-size: 16px;
        }

        .fontSize4 .moreOperator {
            font-size: 20px;
        }

        .jumptoorg {
            display: block;
            margin: 16px 0 16px;
        }

            .jumptoorg a {
            }

        .moreOperator a {
            color: #385487;
        }

        .moreOperator .share {
            border-top: 1px solid #ddd;
        }

            .moreOperator .share a {
                display: block;
                border: 1px solid #ccc;
                border-bottom-style: solid;
                background: #f8f7f1;
                color: #000;
            }

                .moreOperator .share a span {
                    display: block;
                    padding: 10px 10px;
                    text-align: center;
                    border-top: 1px solid #eee;
                    border-bottom: 1px solid #eae9e3;
                    font-weight: bold;
                }

                .moreOperator .share a:hover,
                .moreOperator .share a:active {
                    background: #efedea;
                }

        @@media only screen and (-webkit-min-device-pixel-ratio: 2) {
        }
    </style>
    <script language="javascript" type="text/javascript">
        function auto_remove(img) {
            div = img.parentNode.parentNode; div.parentNode.removeChild(div);
            img.onerror = "";
            return true;
        }

        function changefont(fontsize) {
            if (fontsize < 1 || fontsize > 4) return;
            $('#content').removeClass().addClass('fontSize' + fontsize);
        }

        // 当微信内置浏览器完成内部初始化后会触发WeixinJSBridgeReady事件。
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            //公众号支付
            jQuery('a#getBrandWCPayRequest').click(function (e) {
                WeixinJSBridge.invoke('getBrandWCPayRequest', {
                    "appId": "@ViewData["appId"]", //公众号名称，由商户传入
                        "timeStamp": "@ViewData["timeStamp"]", //时间戳
                        "nonceStr": "@ViewData["nonceStr"]", //随机串
                        "package": "@Html.Raw(ViewData["packageValue"])",//扩展包
                        "signType": "SHA1", //微信签名方式:1.sha1
                        "paySign": "@ViewData["paySign"]" //微信签名
                    }, function (res) {

                        if (res.err_msg == "get_brand_wcpay_request:ok") {
                        }
                        // 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回ok，但并不保证它绝对可靠。
                        //因此微信团队建议，当收到ok返回时，向商户后台询问是否收到交易成功的通知，若收到通知，前端展示交易成功的界面；若此时未收到通知，商户后台主动调用查询订单接口，查询订单的当前状态，并反馈给前端展示相应的界面。
                    });

                });

                WeixinJSBridge.log('yo~ ready.');

            }, false);
                if (jQuery) {
                    jQuery(function () {

                        var width = jQuery('body').width() * 0.87;
                        jQuery('img').error(function () {
                            var self = jQuery(this);
                            var org = self.attr('data-original1');
                            self.attr("src", org);
                            self.error(function () {
                                auto_remove(this);
                            });
                        });
                        jQuery('img').each(function () {
                            var self = jQuery(this);
                            var w = self.css('width');
                            var h = self.css('height');
                            w = w.replace('px', '');
                            h = h.replace('px', '');
                            if (w <= width) {
                                return;
                            }
                            var new_w = width;
                            var new_h = Math.round(h * width / w);
                            self.css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                            self.parents('div.pic').css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                        });
                    });
                }
    </script>
</head>
<body>
    <div class="WCPay">
        <a id="getBrandWCPayRequest" href="javascript:void(0);">
            <h1 class="title">点击提交可体验微信支付</h1>
        </a>
        <p>提示：支付成功后可退款，并体验退款流程</p>
    </div>
</body>
</html>

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/Native.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>无标题页</title>
</head>
<body>
    <form id="form1" runat="server">
        <!--https://chart.googleapis.com/chart?cht=qr&chs=200×200&choe=UTF-8&chld=L|4&chl=http://Codeup.org -->

        <div>

            <center><a href="@ViewData["parm"]">点击支付(微信浏览器)</a><br />扫描支付</br><img src="@ViewData["parm"]" alt="QR code" /></center>
        </div>
    </form>
</body>
</html>

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/NativeCall.cshtml
@*DPBMARK_FILE TenPay*@
@{
                /**/

                Layout = null;
}

<html>
<head>
    <title>NativeCall</title>
</head>
<body>
    <p>@ViewData["payHandler"]</p>
</body>
</html>

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/PayNotifyUrl.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}

<html>
<head>
    <title>PayNotifyUrl</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            @ViewData["payMessage"]
            @ViewData["message"]
        </div>
    </form>
</body>
</html>

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPay/SharedAddress.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>共享地址测试</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            background: #eae9e6;
        }

        body, p, table, td, th {
            font-size: 14px;
            font-family: helvetica,Arial,Tahoma;
        }

        h1 {
            font-family: Baskerville,HelveticaNeue-Bold,helvetica,Arial,Tahoma;
        }

        a {
            text-decoration: none;
            color: #385487;
        }


        .container {
        }

        .title {
        }

        #content {
            padding: 30px 20px 20px;
            color: #111;
            background: #f7f2ed;
        }

        .seeAlso {
            padding: 15px 20px 30px;
        }

        .headpic div {
            margin: 20px 0 0;
        }

        .headpic img {
            display: block;
        }

        .title h1 {
            font-size: 22px;
            font-weight: bold;
            padding: 0;
            margin: 0;
            line-height: 1.2;
            color: #1f1f1f;
        }

        .title p {
            color: #aaa;
            font-size: 12px;
            margin: 5px 0 0;
            padding: 0;
            font-weight: bold;
        }

        .pic {
            margin: 20px 0;
        }

        .articlecontent img {
            display: block;
            clear: both;
            margin: 5px auto;
        }

        .articlecontent p {
            text-indent: 2em;
            font-family: Georgia,helvetica,Arial,Tahoma;
            line-height: 1.4;
            font-size: 16px;
            margin: 20px 0;
        }


        .seeAlso h3 {
            font-size: 16px;
            color: #a5a5a5;
        }

        .seeAlso ul {
            margin: 0;
            padding: 0;
        }

        .seeAlso li {
            font-size: 16px;
            list-style-type: none;
            border-top: 1px solid #ccc;
            padding: 2px 0;
        }

            .seeAlso li a {
                border-bottom: none;
                display: block;
                line-height: 1.1;
                padding: 13px 0;
            }

        .clr {
            clear: both;
            height: 1px;
            overflow: hidden;
        }


        .fontSize1 .title h1 {
            font-size: 20px;
        }

        .fontSize1 .articlecontent p {
            font-size: 14px;
        }

        .fontSize1 .weibo .nickname, .fontSize1 .weibo .comment {
            font-size: 11px;
        }

        .fontSize1 .moreOperator {
            font-size: 14px;
        }

        .fontSize2 .title h1 {
            font-size: 22px;
        }

        .fontSize2 .articlecontent p {
            font-size: 16px;
        }

        .fontSize2 .weibo .nickname, .fontSize2 .weibo .comment {
            font-size: 13px;
        }

        .fontSize2 .moreOperator {
            font-size: 16px;
        }

        .fontSize3 .title h1 {
            font-size: 24px;
        }

        .fontSize3 .articlecontent p {
            font-size: 18px;
        }

        .fontSize3 .weibo .nickname, .fontSize3 .weibo .comment {
            font-size: 15px;
        }

        .fontSize3 .moreOperator {
            font-size: 18px;
        }

        .fontSize4 .title h1 {
            font-size: 26px;
        }

        .fontSize4 .articlecontent p {
            font-size: 20px;
        }

        .fontSize4 .weibo .nickname, .fontSize4 .weibo .comment {
            font-size: 16px;
        }

        .fontSize4 .moreOperator {
            font-size: 20px;
        }

        .jumptoorg {
            display: block;
            margin: 16px 0 16px;
        }

            .jumptoorg a {
            }

        .moreOperator a {
            color: #385487;
        }

        .moreOperator .share {
            border-top: 1px solid #ddd;
        }

            .moreOperator .share a {
                display: block;
                border: 1px solid #ccc;
                border-bottom-style: solid;
                background: #f8f7f1;
                color: #000;
            }

                .moreOperator .share a span {
                    display: block;
                    padding: 10px 10px;
                    text-align: center;
                    border-top: 1px solid #eee;
                    border-bottom: 1px solid #eae9e3;
                    font-weight: bold;
                }

                .moreOperator .share a:hover,
                .moreOperator .share a:active {
                    background: #efedea;
                }

        @@media only screen and (-webkit-min-device-pixel-ratio: 2) {
        }
    </style>
    <script language="javascript" type="text/javascript">
        function auto_remove(img) {
            div = img.parentNode.parentNode; div.parentNode.removeChild(div);
            img.onerror = "";
            return true;
        }

        function changefont(fontsize) {
            if (fontsize < 1 || fontsize > 4) return;
            $('#content').removeClass().addClass('fontSize' + fontsize);
        }

        // 当微信内置浏览器完成内部初始化后会触发WeixinJSBridgeReady事件。
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            //公众号支付
            jQuery('a#getBrandWCPayRequest').click(function (e) {
                WeixinJSBridge.invoke('editAddress', {
                    "appId": "@ViewData["appId"]", //公众号名称，由商户传入
                    "scope": "jsapi_address",//扩展包
                    "signType": "SHA1", //微信签名方式:1.sha1
                    "addrSign": "@ViewData["addrSign"]", //微信签名
                    "timeStamp": "@ViewData["timeStamp"]", //时间戳
                        "nonceStr": "@ViewData["nonceStr"]" //随机串
                    }, function (res) {
                        //若res 中所带的返回值不为空，则表示用户选择该返回值作为收货地址。否则若返回空，则表示用户取消了这一次编辑收货地址。
                        document.form1.address1.value = res.proviceFirstStageName;
                        document.form1.address2.value = res.addressCitySecondStageName;
                        document.form1.address3.value = res.addressCountiesThirdStageName;
                        document.form1.detail.value = res.addressDetailInfo;
                        document.form1.phone.value = res.telNumber;
                    });

                });

                WeixinJSBridge.log('yo~ ready.');

            }, false);
                if (jQuery) {
                    jQuery(function () {

                        var width = jQuery('body').width() * 0.87;
                        jQuery('img').error(function () {
                            var self = jQuery(this);
                            var org = self.attr('data-original1');
                            self.attr("src", org);
                            self.error(function () {
                                auto_remove(this);
                            });
                        });
                        jQuery('img').each(function () {
                            var self = jQuery(this);
                            var w = self.css('width');
                            var h = self.css('height');
                            w = w.replace('px', '');
                            h = h.replace('px', '');
                            if (w <= width) {
                                return;
                            }
                            var new_w = width;
                            var new_h = Math.round(h * width / w);
                            self.css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                            self.parents('div.pic').css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                        });
                    });
                }
    </script>
</head>
<body>
    <div class="WCPay">
        <a id="getBrandWCPayRequest" href="javascript:void(0);">
            <h1 class="title">点击体验共享地址</h1>
        </a>

    </div>
</body>
</html>